# -*- coding: utf-8 -*-
"""marathon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14yZQhXE5L7MERUl-Jx8EithRXV4d0zCi

# INSTALLING PYQRCODE MODULE
"""

!pip install pyqrcode

"""# IMPORTING ALL NECESSARY LIBRARIES"""

import requests
import json
from openpyxl import Workbook
from openpyxl import load_workbook
import pyqrcode
from PIL import Image
import time

"""# CONVERTING DATA FROM DATAFRAME TO JSON FORMAT AND POST IT TO SERVER AND CREATING A DYNAMIC QR CODE FOR USER AFTER FETCHING REQUESTS FROM SERVER USING GET METHOD"""

def jsonconversion(eventname,eventdate,name,phone,email,emername,emernumber,size,category,bib,g):
  if g==1:
    data={
        "eventName":eventname,
        "eventDate":eventdate,
        "participantName":name,
        "phoneNumber":phone,
        "mailId":email,
        "emergencyContactName":emername,
        "emergencyContactNumber":emernumber,
        "tShirtSize":size,
        "category":category,
        "bibNumber":bib,
        "bibCollector":"",
        "bibCollectorIdLocation":"",
        "bibCollectedOn":""
        }

    data=json.dumps(data)
    print(json.dumps(data))
    try:
      response = requests.post(url="https://iemregister.commonsensetechnologies.in/v1/api/register",
                               headers={"content-type":"application/json","api":"547d1ee7-4843-11ea-b4b9-0a14cb376790"},data=data)
      print(response.text)
    except Exception as e:
      print(e)
      
  else:
    PARAMS = {"eventName":eventname,
              "eventDate":eventdate,
              "bibNumber":bib
              }
    try:
      r = requests.get(url = "https://iemregister.commonsensetechnologies.in/v1/api/get",
                       headers={"content-type":"application/json","api":"547d1ee7-4843-11ea-b4b9-0a14cb376790"},
                       params = PARAMS)
      # extracting data in json format
      data = r.json()
      idno = data["id"]
      bibno = data["bibNumber"]
      url = "https://iemqr.commonsensetechnologies.in/qr?uid="+str(idno)+"&bib="+str(bibno)
      print(idno)
      print(bibno)
      image = pyqrcode.create(url)
      image.png("/content/drive/My Drive/test_image3/"+f"{bibno}.png",scale=5)
      im = Image.open("/content/drive/My Drive/test_image3/"+f"{bibno}.png")
      im = im.convert("RGBA")
      w,h = im.size
      logo = Image.open("/content/bunny.png")
      box = (w//2-25,w//2-25,w//2+25,w//2+25)
      im.crop(box)
      region = logo
      region = region.resize((box[2] - box[0], box[3] - box[1]))
      im.paste(region,box)
      im.save("/content/drive/My Drive/test_image3/"+f"{bibno}.png") 
    
    except Exception as e:
      print(e)

"""# EXECUTION OF THE PREVIOUS STEP BY CALLING THE FUNCTION"""

filename= "output (4).xlsx"
wb=load_workbook(filename)
sheet=wb.worksheets[0]
print("Enter 1 for posting request and 2 for getting request")
g = int(input("Enter your Choice : "))
for i in range(2,9):
  time.sleep(1)
  print(i)
  eventname="IEM UEM MARATHON 2020"
  eventdate="2020-02-09"
  name=str(sheet.cell(row=i,column=6).value)
  phone=str(sheet.cell(row=i,column=7).value)
  email=str(sheet.cell(row=i,column=5).value)
  emername=str(sheet.cell(row=i,column=10).value)
  emernumber=str(sheet.cell(row=i,column=11).value)
  size=str(sheet.cell(row=i,column=9).value)
  category=str(sheet.cell(row=i,column=4).value)
  bib=str(sheet.cell(row=i,column=2).value)
  #bib=str(sheet.cell(row=i,column=3).value)#Typecast to string
  print(eventname+eventdate+name+bib+phone+email+emername+emernumber+size+category)
  jsonconversion(eventname,eventdate,name,phone,email,emername,emernumber,size,category,bib,g)#Typecast to string

1